### ISSUE TITLE
QB4.5 BC.EXE works / LINK.EXE fails...

### ISSUE THREAD

**Issue by DualBrain** [morphx666/x8086NetEmu#7]
Found another strange situation that seems like it might be useful to investigate further...

After playing around with QBASIC.EXE; what would happen if I tried to use QB4.5.  The QB.EXE executable exhibits similar behavior as QBASIC.EXE; however, there are other files that could be used to explore.  I set out to compile some code:

Same TEST.BAS as the QBASIC.EXE ticket.

BC - works.  Builds a .OBJ file (whether or not it's correct might be suspect... see below.)
LINK - fails with:

> LINK : fatal error L1104: BRUN45.LIB : not valid library

This same process works as expected in DosBox.  The resulting EXE built in DosBox copied to here also works as expected.  So programs compiled in QB45 appear to work.  I also have some TSR's that are built in QB45 along with other tools... those also appear to work as expected.

It is also interesting to note that the text being presented is all displayed... unlike what happens when trying to use:

`C:\>QB /?`

I started to think that maybe there is something "odd" with ANSI.SYS not being loaded.  With it loaded, still the same problems.  I also confirmed that it appears to be working using a custom prompt using ANSI characters.  So don't think that's the problem.

To make things even more interesting, I have an old XREF tool (Don Malin's Cross Reference Program (c) 1992 v 2.24).  This tool appears to have the same menu UI and overall user interface elements... and works.

**Comment by morphx666** [comment]
I've just found another program with the exact same problem(s), Microsoft (R) BASIC Professional Development System 7.10

- The weird sequences of letters...
- And as with defrag.exe, the background is not properly filled

![image](https://user-images.githubusercontent.com/12353675/56267110-dfb76600-60bb-11e9-87ff-ef24b569bd83.png)

![image](https://user-images.githubusercontent.com/12353675/56267210-2c02a600-60bc-11e9-9125-3ac7ada178c9.png)

I've also found that nssi.exe (a hardware diagnostics tool, similar to CheckIt and SysChk) fails to load.

I really wish I could find a small program (preferably a .com) that presented the same symptoms so that I could "easily" debug it.

**Comment by morphx666** [comment]
This has been fixed since commit 375e50b42557459545b2edcb6e8a2fb39fc8903f
